config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :routes do
    resources :points, only: :create
    resources :favorites, only: :create
    resources :rides, only: %i[new create] do
      member do
        patch :mark_as_done
      end
    end
    resources :pinned_routes, only: :create
  end
  resources :favorites, only: %i[index destroy]
  resources :rides, only: %i[index destroy]

  # get '/test', to: 'pages#test'
  get '/myroutes', to: 'routes#my_routes', as: :my_routes
  get '/routes/:id/record', to: 'routes#record', as: :record
  patch '/routes/:id/register', to: 'routes#register', as: :register
  delete '/photos/:id', to: 'routes#delete_image_attachment', as: :delete_route_photo
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 fade-out" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 fade-out" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
      <ul class="footer-menu">
        <li>
          <%= link_to root_path, class: 'text-center' do %>
            <i class="fa-solid fa-house"></i>
            <span>Home</span>
          <% end  %>
        </li>
        <li>
          <%= simple_form_for Route.new do |f| %>
            <button type="submit" class='icon-button'>
              <i class="fa-solid fa-record-vinyl" style="cor-06"></i>
              <span>Record</span>
            </button>
          <% end %>
        </li>
        <li>
          <%= link_to favorites_path, class: 'text-center' do %>
            <i class="fa-solid fa-heart" style="cor-06"></i>
            <span>Save</span>
          <% end %>
        </li>
        <li>
          <%= link_to routes_path, class: 'text-center' do %>
            <i class="fa-solid fa-magnifying-glass"></i>
            <span>Find</span>
          <% end %>
        </li>
      </ul>
  </div>
</footer>

app/views/shared/_map.html.erb
<div style="width: 100%; height: <%= height %>;" class='<%= html_options[:class]%>'
  data-route-tracking-target='map'
  data-controller="map"
  data-map-markers-value="<%= markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.svg" %>
    <% end %>
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <% if !user_signed_in? %>
        <%= image_tag "user.svg", class: "avatar-icon"%>
      <% elsif current_user.photo.attached? %>
        <div class="picture-round">
          <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
        </div>
      <% else %>
        <%= image_tag "user.svg", class: "avatar-icon"%>
      <% end %>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Created Routes", my_routes_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown d-none d-sm-block">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "user.svg", class: "avatar"%>
              <% end %>
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_route_card.html.erb
<div class="card-product">
  <div class="pin-icon">
    <% if current_user&.pinned_route == route %>
      <%= link_to route_pinned_routes_path(current_user.pinned_route), class: "pin-button", remote: true, data: { controller: "pin-button", action: "ajax:success->pinButton#handleSuccess", turbo_method: :post } do %>
        <%= image_tag 'pin-verde-2.svg', data: { target: "pinButton.pinImage" } %>
      <% end %>
    <% else %>
      <%= link_to route_pinned_routes_path(route_id: route.id), class: "pin-button", remote: true, data: { controller: "pin-button", action: "ajax:success->pinButton#handleSuccess", turbo_method: :post } do %>
        <%= image_tag 'pin-branco-2.svg', data: { target: "pinButton.pinImage" } %>
      <% end %>
    <% end %>
  </div>

    <%= link_to route do  %>
      <% if route.photos.attached? %>
        <%= cl_image_tag route.photos[0].key, class: "product-image primary-image", data: { 'picker-target': "pimage" } %>
      <% else %>
        <% default_image_url = case route.type_of_route
                              when "Urban"
                                then "urban.webp"
                              when "Suburban"
                                then "suburban.webp"
                              when "CountrySide"
                                then "countryside.webp"
                              when "Mountain"
                                then "mountain.webp"
                              when "Beach"
                                then "photo-beach.jpg"
                              end
        %>
        <%= image_tag default_image_url, class: "product-image primary-image" %>
      <% end %>
     <% end %>

    <div class="card-route-details">
      <ul>
        <li><span class="type"><%= route.type_of_route %></span></li>
        <li><h3 class="card-tit"><%= link_to route.name, route %></h3></li>
        <li><p><%= route.description %></p></li>
        <li>
          <span class="distance">
            Distance:
            <% if route.distance.present? %>
              <%= route.distance < 1000 ? "#{route.distance}m" : "#{(route.distance / 1000.0).round(2)}km" %>
            <% else %>
              Not Available
            <% end %>
          </span>
        </li>
      </ul>

      <% favorite = Favorite.where(route: route, user: current_user).first %>
      <% if favorite.present? %>
        <%= link_to favorite_path(favorite, path: request.original_fullpath), class: "bookmark", data: { controller: "favorites", action: "toggleFavorite", turbo_method: :delete } do %>
          <%= route.favorites.size %> <i class="fa-solid fa-heart" data-target="favorites.heart"></i>
        <% end %>
      <% else %>
        <%= link_to route_favorites_path(route, path: request.original_fullpath), class: "bookmark", data: { controller: "favorites", action: "toggleFavorite", turbo_method: :post } do %>
          <%= route.favorites.size %> <i class="fa-sharp fa-regular fa-heart" data-target="favorites.heart"></i>
        <% end %>
      <% end %>
    </div>


</div>

app/views/shared/_route_cards_horizontal.html.erb
<ul class="gallery">
  <% routes.each do |route| %>
    <li>
      <%= render partial: 'shared/route_card', locals: { route: route } %>
    </li>
  <% end %>
  <li>
    <%= link_to routes_path do %>
      <%= image_tag "arrow-right.svg", class:"button-arrow-right" %>
    <% end %>
  </li>
</ul>

app/views/shared/_route_cards_vertical.html.erb
<div>
  <ul class="gallery-vertical">
    <% routes.each do |route| %>
      <li>
        <%= render partial: 'shared/route_card', locals: { route: route } %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_route_photo.html.erb
<li>
  <%= cl_image_tag photo.key %>
  <%  photo_poster = User.find(photo.metadata[:user_id]) %>
  <div class="picture-poster">
    <% if photo_poster.photo.attached? %>
      <%= cl_image_tag photo_poster.photo.key, class: "avatar", alt: "dropdown menu" %>
    <% else %>
      <%= image_tag "user.svg", class: "avatar"%>
    <% end %>
  </div>
  <% if policy(route).delete_photo?(photo) && request.path == edit_route_path(route)  %>
    <div class="picture-discard">
      <%= link_to delete_route_photo_path(photo), data: { turbo_method: :delete, turbo_frame: 'delete_photo', turbo_confirm: "Delete photo?" } do %>
        <i class="fa-regular fa-x"></i>
      <% end %>
    </div>
  <% end %>
</li>

app/views/shared/_route_photos.html.erb
<%= turbo_frame_tag 'delete_photo' do %>
  <% if route.photos.attached?%>
    <ul class="route-pictures">
      <% route.photos.each do |photo| %>
        <%= render 'shared/route_photo', photo: photo, route: route %>
      <% end %>
    </ul>
  <% end  %>
<% end %>

app/views/shared/_route_recorder.html.erb
<!--<div data-controller = 'route-tracking' data-route-tracking-id-value='<%= route.id %>'>
  <button class='btn btn-primary' data-route-tracking-target='startstop' data-action='click->route-tracking#trackRoute'>Track Route</button>
  <%= link_to 'Save', '#', data: { route_tracking_target: 'save' }, class: 'btn btn-success d-none' %>
  <%= link_to 'Discard', route_path(route), onclick: flash[:notice] = 'Route discarded', data: { route_tracking_target: 'discard', turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger d-none' %>
  <p data-route-tracking-target = 'status'></p>
  <p data-route-tracking-target = 'position'></p>
</div>

app/views/shared/_searchbar.html.erb
<!-- Button trigger modal -->
<div class="row g-0 d-flex align-items-start search-bar">
  <div class="col-sm col-lg-6 offset-lg-3 border-end-0">
    <%= simple_form_for :search, url: routes_path, method: "GET", html: { } do |f| %>
      <div class="search-icon">
        <i class="fas fa-search" style="color: var(--cor-8);"></i>
      </div>
      <%= f.input :address, input_html: { value: address, class: "search-input" }, label: false, required: false, placeholder:"Search City ex: Ribeirão Preto" %>
    <% end %>
  </div>
  <div class="col-auto border-0 search-filter">
    <button type="button" class="btn btn-filter" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="fas fa-sliders" style="color: var(--cor-1);"></i>
    </button>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content rounded-16">
      <div class="modal-header">
        <h1 class="modal-title cor-10 font-1-xl fs-5" id="exampleModalLabel">Find a route</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for :search, url: routes_path , method: "GET", html: {class: 'form-inline' } do |f| %>
            <%= f.input :address, input_html: {value: @address }, label: false, required: false, placeholder:"Search City ex: Ribeirão Preto"  %>
            <div class="range" data-controller= "slider" >
              <div class="range-price d-flex justify-content-between align-items-start mt-2 mb-2">
                <%= f.input :min, label: "min", wrapper_html: { class: 'mb-0', remove_class: 'mb-3' }, label_html: {class: 'text-center'}, input_html: { readonly: true, class:'minValue text-center', value: min_distance, type: 'number', data: { slider_target: "minvalue", action: 'input->slider#changeValue' } }, required: false %>
                <p>Route Distance (km)</p>
                <%= f.input :max, label: "max", wrapper_html: { class: 'mb-0', remove_class: 'mb-3' }, label_html: {class: 'text-center'}, input_html: { readonly: true, class:'maxValue text-center', value: max_distance, type: 'number' , data: { slider_target: "maxvalue", action: 'input->slider#changeValue' } }, required: false %>
                <%# <label for="min">Min</label> %>
                <%# <input type="number" name="min" value="300" data-slider-target= "minvalue" data-action='input->slider#changeValue'>
                <label for="max">Max</label>
                <input type="number" name="max" value="700" data-slider-target= "maxvalue" data-action='input->slider#changeValue'> %>
              </div>
              <div class="range-slider">
                  <span class="range-selected" data-slider-target= "range" style="left:<%= "#{(min_distance.to_f / 100) * 100}%" %>; right: <%="#{100 - (max_distance.to_f / 100) * 100}%" %>"></span>
              </div>
              <div class="range-input">
                <input type="range" class="min" min="0" max="100" value="<%= min_distance %>" step="1" data-slider-target= "minslider" data-action='input->slider#changeRange'>
                <input type="range" class="max" min="0" max="100" value="<%= max_distance %>" step="1" data-slider-target= "maxslider" data-action='input->slider#changeRange'>
              </div>
            </div>

            <%= f.input :type_of_route, label: false, as: :select, collection: Route::TYPE_OF_ROUTE, prompt: 'Choose route type', include_blank: "All Types", input_html: { class: 'mt-4' }, selected: type_of_route, required: false  %>
            <%= f.submit "Search", class: "btn btn-primary w-100" %>
          <% end %>
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>

app/views/shared/_type_cards_horizontal.html.erb
<div class="background-gallery-vertical-type mb-5">
  <div class="container type-routes">
    <h2 class="font-1-xl cor-11 pb-3">Browse by type of routes</h2>
    <ul class="gallery-vertical-type">
      <li>
        <div class="card-type">
          <%= link_to routes_path(search: { type_of_route: "Urban" }), class: 'text-center', method: :get do %>
            <%= image_tag "urban.webp" %>
            <span>Urban</span>
          <% end %>
        </div>
      </li>

      <li>
        <div class="card-type">
          <%= link_to routes_path(search: { type_of_route: "Suburban" }), class: 'text-center', method: :get do %>
            <%= image_tag "suburban.webp" %>
            <span>Suburban</span>
          <% end %>
        </div>
      </li>

      <li>
        <div class="card-type">
          <%= link_to routes_path(search: { type_of_route: "CountrySide" }), class: 'text-center',  method: :get do %>
            <%= image_tag "countryside-2.webp" %>
            <span>CountrySide</span>
          <% end %>
        </div>
      </li>

    <li>
      <div class="card-type">
        <%= link_to routes_path(search: { type_of_route: "Mountain" }), class: 'text-center', method: :get do %>
          <%= image_tag "mountain.webp" %>
          <span>Mountain</span>
        <% end %>
      </div>
    </li>

    <li>
      <div class="card-type">
        <%= link_to routes_path(search: { type_of_route: "Beach" }), class: 'text-center', method: :get do %>
          <%= image_tag "photo-beach.jpg" %>
          <span>Beach</span>
        <% end %>
      </div>
    </li>
  </ul>
</div>