config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :routes do
    resources :points, only: :create
    resources :favorites, only: :create
    resources :rides, only: %i[new create] do
      member do
        patch :mark_as_done
      end
    end
    resources :pinned_routes, only: :create
  end
  resources :favorites, only: %i[index destroy]
  resources :rides, only: %i[index destroy]

  # get '/test', to: 'pages#test'
  get '/myroutes', to: 'routes#my_routes', as: :my_routes
  get '/routes/:id/record', to: 'routes#record', as: :record
  patch '/routes/:id/register', to: 'routes#register', as: :register
  delete '/photos/:id', to: 'routes#delete_image_attachment', as: :delete_route_photo
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/route.rb
require "json"
require "open-uri"

class Route < ApplicationRecord
  include PgSearch::Model
  belongs_to :creator, class_name: "User"
  has_many :rides
  has_many :points, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many_attached :photos


  validates :name, presence: true, length: { minimum: 5 }
  validates :type_of_route, presence: true

  TYPE_OF_ROUTE = ['Urban', 'Suburban', 'CountrySide', 'Mountain', 'Beach']

  # pg_search_scope :search_by_type_of_route, against: :type_of_route

  # pg_search_scope :search_by_distance, against: :distance

  def total_distance
    distance = 0
    (points.length - 1).times do |i|
      distance += Point.distance_between(points[i], points[i + 1]) # Delta in meters
    end
    distance.to_i
  end

  def total_positive_elevation
    n = points.length - 1 # Number of intervals between points
    if n > 100
      interval = n.to_f / (100 - 1) # Interval size

      sampled_points = []
      (0...100).times do |i|
        sampled_points << points[(interval * i).round] # getting elements at even intervals
      end
    else
      sampled_points = points
    end

    positive_elevation = 0
    # negative_elevation = 0
    elevations = sampled_points.map do |point|
      url = "https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2/tilequery/#{point.longitude},#{point.latitude}.json?limit=50&layers=contour&access_token=#{ENV['MAPBOX_API_KEY']}"
      response = URI.open(url).read
      JSON.parse(response)['features'].last['properties']['ele']
    end
    (elevations.length - 1).times do |i|
      positive_elevation += elevations[i + 1] > elevations[i] ? elevations[i + 1] - elevations[i] : 0
      # negative_elevation -= elevations[i + 1] < elevations[i] ? elevations[i + 1] - elevations[i] : 0
    end
    # p negative_elevation
    positive_elevation
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_route, only: %i[show destroy edit update record register]

  after_action :skip_authorization, only: %i[my_routes]
  after_action :verify_policy_scoped, only: %i[my_routes], unless: :skip_pundit?


  def index
    @routes = Route.includes(:favorites).where.not(name: nil)
    @address = ""
    @min_distance = 0
    @max_distance = 100
    @type_of_route = nil

    if params[:search].present?
      @type_of_route = params[:search][:type_of_route]
      @routes = @routes.where(type_of_route: @type_of_route) if @type_of_route.present?
      if params[:search][:address] || params[:search][:min] || params[:search][:max]

        @address = params[:search][:address]

        if params[:search][:min].present?
          @min_distance = params[:search][:min].to_i
          @max_distance = params[:search][:max].to_i
        end
        @type_of_route = params[:search][:type_of_route]
        @routes = @routes.where("distance >= ? AND distance <= ?", @min_distance * 1000, @max_distance * 1000)
      end
      if @address.present?
        points = Point.near(@address, 10)
        @routes = @routes.where(id: points.map(&:route).pluck(:id).uniq)
      end
    end
  end

  def my_routes
    @my_routes = policy_scope(Route).where(creator: current_user).where.not(name: nil)
  end

  def show
    authorize @route
    @ride = Ride.new
    @ride_on_going = Ride.where(done: false).where(user: current_user)
    @favorite = Favorite.where(route: @route, user: current_user)
    @markers = @route.points.map do |point|
      {
        lat: point.latitude,
        lng: point.longitude
      }
    end
  end

  def create
    @route = Route.new
    authorize @route
    @route.creator = current_user
    # destroy incompleted routes
    Route.where(creator: current_user).where(name: nil).each(&:destroy)
    if @route.save(validate: false)
      redirect_to record_path(@route)
    else
      render :new, error: :unprocessable_entity
    end
  end

  def record
    authorize @route
    respond_to do |format|
      if @route.points.empty?
        format.html
        format.text { render partial: "shared/map", locals: { markers: @markers, height: "300px", html_options: { class: 'd-none' } }, formats: [:html] }
      else
        @markers = @route.points.map { |point| { lat: point.latitude, lng: point.longitude } }
        format.html
        format.text { render partial: "shared/map", locals: { markers: @markers, height: "300px", html_options: { class: '' } }, formats: [:html] }
      end
    end
  end

  def register
    authorize @route
    if @route.points.size < 2
      redirect_to register_path(@route), alert: "Not enough tracking data"
    elsif @route.update(route_params.except('photos'))
      @route.distance = @route.total_distance
      @route.positive_elevation = @route.total_positive_elevation
      if params[:route][:photos].present?
        params[:route][:photos][1..].each do |photo|
          @route.photos.attach(io: photo,
                               filename: photo.original_filename,
                               content_type: photo.content_type,
                               metadata: { user_id: current_user.id })
        end
      end
      @route.save
      redirect_to route_path(@route), notice: "Route successfully shared!"
    else
      render :record, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @route
    @route.destroy
    redirect_to routes_path, notice: "Route succesfully deleted"
  end

  def delete_image_attachment
    @route_photo = ActiveStorage::Attachment.find(params[:id])
    @route_photo.purge
    redirect_back(fallback_location: request.referer)
  end

  def edit
    authorize @route
    @route.photos.build if @route.photos.blank?
    respond_to do |format|
      if turbo_frame_request?
        format.html { render partial: 'shared/route_photos', locals: { route: @route } }
      else
        format.html
      end
    end
  end

  def update
    authorize @route
    if params[:route][:photos].present?
      params[:route][:photos][1..].each do |photo|
        @route.photos.attach(io: photo,
                             filename: photo.original_filename,
                             content_type: photo.content_type,
                             metadata: { user_id: current_user.id }
                            )
      end
    end
    if @route.update(route_params.except('photos'))
      redirect_to route_path(@route), notice: "Your route was updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # def update
  #   if @route.save?
  #     redirect_to route_path(@route)
  #   else
  #     render :edit, error: :unprocessable_entity
  #   end
  # end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, :description, :distance, :type_of_route, :positive_elevation, photos: [])
  end
end


  # # Build the SQL query using ActiveRecord syntax
  # query = <<-SQL
  #   SELECT DISTINCT routes.*
  #   FROM routes
  #   INNER JOIN points ON points.route_id = routes.id
  #   WHERE (

    #     2 * 6371 * asin(
      #       sqrt(
        #         sin((radians(points.latitude) - radians(?)) / 2) * sin((radians(points.latitude) - radians(?)) / 2) +
        #         cos(radians(?)) * cos(radians(points.latitude)) *
        #         sin((radians(points.longitude) - radians(?)) / 2) * sin((radians(points.longitude) - radians(?)) / 2)
        #       )
        #     )
        #   ) <= ?
        # SQL

        # # Execute the query using ActiveRecord
        # routes_within_radius = Route.find_by_sql([query, user_latitude, user_latitude, user_latitude, user_longitude, user_longitude, radius_km])



      #   if @address.present? && (params[:search][:distance] == "0") && !(@type_of_route.present?)
      #     address = params[:search][:address]
      #     coordinates = Geocoder.coordinates(address)
      #     latitude = coordinates[0]
      #     longitude = coordinates[1]
      #     radius = 10
      #     query = <<-SQL
      #       SELECT DISTINCT routes.*
      #       FROM routes
      #       INNER JOIN points ON points.route_id = routes.id
      #       WHERE (
      #       2 * 6371 * asin(
      #         sqrt(
      #           sin((radians(points.latitude) - radians(?)) / 2) * sin((radians(points.latitude) - radians(?)) / 2) +
      #           cos(radians(?)) * cos(radians(points.latitude)) *
      #             sin((radians(points.longitude) - radians(?)) / 2) * sin((radians(points.longitude) - radians(?)) / 2)
      #             )
      #           )
      #         ) <= ?
      #     SQL
      #     #   # Execute the query using ActiveRecord
      #     @routes = policy_scope(Route).find_by_sql([query, latitude, latitude, latitude, longitude, longitude, radius])
      #   elsif params[:search][:distance] != "0" && !(params[:search][:address].present?) && !(params[:search][:type_of_route].present?)

app/views/routes/edit.html.erb
<div class="container mt-4">
  <h1 class="mb-3 cor-11 font-1-xl">Edit Route</h1>

  <% if !@route.photos.reject {|photo| photo.id.nil? }.empty? %>
    <%= render 'shared/route_photos', route: @route %>
  <% end %>

  <%= simple_form_for @route do |f| %>
      <% if @route.creator == current_user  %>
        <%= f.input :description, label: 'Description', placeholder: 'ex: Trilha leve, muito agradável' %>
      <% end %>
      <%= f.input :photos, as: :file, input_html: { multiple: true} %>
      <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "Back", route_path(@route) %>
</div>

app/views/routes/index.html.erb
<div class="container mt-4">
  <h1 class="mb-3 cor-11 font-1-xl">Routes</h1>
  <%= render "shared/searchbar", address: @address, type_of_route: @type_of_route, min_distance: @min_distance, max_distance: @max_distance %>
  <% if @routes.blank? %>
    <p>No routes in this location</p>
  <% else %>
    <%= render "shared/route_cards_vertical", routes: @routes %>
  <% end %>
</div>

app/views/routes/my_routes.html.erb
<div class="container mt-4">
<h1 class="mb-3 cor-11 font-1-xl">My Posted Routes</h1>

<% if @my_routes.blank? %>
  <p>No routes created</p>
<% else %>
  <%= render "shared/route_cards_vertical", routes: @my_routes %>
<% end %>
</div>

app/views/routes/record.html.erb
  <div data-controller = 'route-tracking' data-route-tracking-id-value='<%= @route.id %>'>
      <div class="navbar-record">
        <div class="d-flex justify-content-between align-items-center gap-3 container pt-2 pb-2">
          <%= link_to route_path(@route), data: { route_tracking_target: 'discard', turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'd-none close-button' do  %>
            <i class="fa-regular fa-x"></i>
          <% end %>
          <h1 class="cor-11 font-1-m-b text-center w-100 m-auto">Tracking Route</h1>
          <button class='btn-save d-none' data-route-tracking-target='save' data-action='click->route-tracking#showForm'>Save</button>
        </div>
      </div>
      <div class='record-top-half-display d-flex justify-content-center'>
          <%= image_tag('recording.gif', class: 'd-none', data: { route_tracking_target: 'recordgif'} )%>
        <%= render "shared/map", markers: @markers ? @markers : [], height: "300px", html_options: { class:  @markers ? '' : 'd-none' }%>
      </div>
      <div class="container mt-3">
      <div class="d-flex flex-column align-items-center"  data-route-tracking-target='tracker' class=<%= 'd-none' if @route.errors.any? %>>
        <button class='btn-record mb-2 mt-3' data-route-tracking-target='startstop' data-action='click->route-tracking#trackRoute'>Track Route</button>
        <div class="recording mt-4">
          <p data-route-tracking-target='status', class='font-2-m cor-11 text-center mb-2'></p>
          <p data-route-tracking-target='position', class='font-2-xs cor-8 text-center'></p>
        </div>
      </div>

    <%= simple_form_for @route, url: register_path(@route), method: 'PATCH', html: { class: @route.errors.any? ? "" : "d-none", data: { route_tracking_target: 'registerform'} } do |f| %>
    <h2 class="mb-3 cor-11 font-1-m-b">Post your route</h2>
      <div class="form-inputs cor-9 font-2-xs">
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :type_of_route, collection: Route::TYPE_OF_ROUTE %>
        <%= f.input :photos, as: :file, input_html: {multiple: true, class: "cor-9 font-2-xs"}  %>
        <div class="form-actions">
          <%= f.button :submit, "Post Route", class:"btn-primary btn-block mb-3 w-100" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/routes/show.html.erb
<div class="map-show">

  <div class style="width: 100%; height: 360px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

    <div class="route-title-show" id="show-route-name">
      <div class="container">
        <h1 class="font-1-m-b cor-11 title-show text-center"><%= @route.name %></span></h1>
      </div>
    </div>


    <div class='route-creator-show d-flex align-items-center justify-content-end'>
    <h3 class="font-2-xss cor-11">Created by <%= @route.creator.first_name %></h3>
    <% if @route.creator.photo.attached? %>
      <div class="picture-round">
          <%= cl_image_tag @route.creator.photo.key, class: "avatar", alt: "dropdown menu" %>
      </div>
    <% else %>
      <%= image_tag "user.svg", class: "avatar-show"%>
    <% end %>
  </div>

</div>

<div class="container mt-3 mb-4">

  <div class="route-details-show mt-4 mb-4">
    <ul>
      <div class="details-type d-flex gap-2 mt-3 mb-2">
      <li class="d-flex flex-column align-items-center"><span class="font-2-xss cor-8">Type of Route</span><span class="font-2-s cor-11"><%= @route.type_of_route %></span></li>
      <li class="d-flex flex-column align-items-center"><span class="font-2-xss cor-8">Distance</span> <span class="font-2-s cor-11"> <%= @route.distance < 1000 ? "#{@route.distance}m" : "#{(@route.distance / 1000.0).round(2)}km" %></span></li>
      <li class="d-flex flex-column align-items-center"><span class="font-2-xss cor-8">Elevation</span> <span class="font-2-s cor-11"> <%= @route.positive_elevation.nil? ? '60m' : "#{@route.positive_elevation.to_i}m" %></span></li>
      </div>
      <li><p class="font-2-s cor-11"><%= @route.description %></p></li>
    </ul>

    <div class="favorite-show">
      <% if @favorite.present? %>
        <%= link_to favorite_path(@favorite.first, path: request.original_fullpath), data: { turbo_method: :delete } do  %>
          <i class="fa-solid fa-heart" style="color:var(--cor-11)"></i>
      <% end %>
      <% else %>
        <%= link_to route_favorites_path(@route, path: request.original_fullpath), data: { turbo_method: :post } do  %>
          <i class="fa-regular fa-heart" style="color: var(--cor-11)"></i>
        <% end %>
      <% end %>
    </div>
  </div>

  <%= render 'shared/route_photos', route: @route %>

 </div>

  <div class="buttons-show">
    <% if policy(@route).edit_description? %>
      <%= link_to "Edit", edit_route_path(@route), class: 'btn btn-primary' %>
    <% elsif user_signed_in? %>
      <%= link_to "Add Photos", edit_route_path(@route), class: 'btn btn-back' %>
    <% end %>
    <% if policy(@route).destroy? %>
      <%= link_to "Delete", route_path(@route), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    <% end %>

    <%#if @ride_on_going.any? %>
        <%#= button_to "Stop", mark_as_done_route_ride_path(@route, @ride_on_going.first), remote: true, data: {turbo_method: :patch}, class: "btn-start-stop-show" %>
    <%# else %>
      <%##= simple_form_for [@route,@ride] do |f| %>
        <%#= f.submit "Start", class: "btn-start-stop-show"%>
      <%# end %>
    <%# end %>

    <%= link_to route_pinned_routes_path(@route), class: "", remote: true, data: { turbo_method: :post } do %>
      <% if current_user.pinned_route == @route %>
        <%= image_tag 'pin-verde-2.svg' %>
      <% else %>
        <%= image_tag 'pin-branco-2.svg' %>
      <% end %>
    <% end %>
  </div>
</div>